---
- hosts: webservers
  become: yes
  vars_files:
  - confidential.yml
  tasks:
  
  - name: Install httpd.
    package: 
      name: httpd
      state: latest
    notify: httpd service
    tags:
    - base-install

  handlers:

  - name: restart ans enable httpd.
    service:
      name: httpd
      state: restarted
      enabled: yes
    listen: httpd service
